// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMS_TYNB.Models.Master;

#nullable disable

namespace SMS_TYNB.Migrations.Master
{
    [DbContext(typeof(VnptSmsBrandnameContext))]
    [Migration("20250730091840_InitVnptSmsBrandname")]
    partial class InitVnptSmsBrandname
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SMS_TYNB.Models.Master.Config", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("IsUsed")
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Config");
                });

            modelBuilder.Entity("SMS_TYNB.Models.Master.MEmployee", b =>
                {
                    b.Property<long>("IdEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<long>("IdOrganization")
                        .HasColumnType("bigint");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PhoneNumberSend")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("IdEmployee");

                    b.ToTable("m_employee");
                });

            modelBuilder.Entity("SMS_TYNB.Models.Master.MFile", b =>
                {
                    b.Property<long>("IdFile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("IdOrganization")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdFile");

                    b.ToTable("m_file");
                });

            modelBuilder.Entity("SMS_TYNB.Models.Master.MGroup", b =>
                {
                    b.Property<long>("IdGroup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long?>("IdGroupParent")
                        .HasColumnType("bigint");

                    b.Property<long>("IdOrganization")
                        .HasColumnType("bigint");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("IdGroup");

                    b.ToTable("m_group");
                });

            modelBuilder.Entity("SMS_TYNB.Models.Master.MGroupEmployee", b =>
                {
                    b.Property<long>("IdGroupEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("IdEmployee")
                        .HasColumnType("bigint");

                    b.Property<long>("IdGroup")
                        .HasColumnType("bigint");

                    b.HasKey("IdGroupEmployee");

                    b.ToTable("m_group_employee");
                });

            modelBuilder.Entity("SMS_TYNB.Models.Master.MHistory", b =>
                {
                    b.Property<long>("IdHistory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("IdRecord")
                        .HasColumnType("bigint");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdHistory");

                    b.ToTable("m_history");
                });

            modelBuilder.Entity("SMS_TYNB.Models.Master.MSms", b =>
                {
                    b.Property<long>("IdSms")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long>("IdOrganization")
                        .HasColumnType("bigint");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<int?>("NumberMessageError")
                        .HasColumnType("int");

                    b.Property<int?>("NumberMessages")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("IdSms");

                    b.ToTable("m_sms");
                });

            modelBuilder.Entity("SMS_TYNB.Models.Master.MSmsEmployee", b =>
                {
                    b.Property<long>("IdSmsEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("ERROR")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ERROR_DESC")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("IdEmployee")
                        .HasColumnType("bigint");

                    b.Property<long>("IdGroup")
                        .HasColumnType("bigint");

                    b.Property<long>("IdSms")
                        .HasColumnType("bigint");

                    b.Property<string>("REQID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdSmsEmployee");

                    b.ToTable("m_sms_employee");
                });

            modelBuilder.Entity("SMS_TYNB.Models.Master.MSmsFile", b =>
                {
                    b.Property<long>("IdSmsFile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("IdFile")
                        .HasColumnType("bigint");

                    b.Property<long>("IdSms")
                        .HasColumnType("bigint");

                    b.HasKey("IdSmsFile");

                    b.ToTable("m_sms_file");
                });

            modelBuilder.Entity("SMS_TYNB.Models.Master.Organization", b =>
                {
                    b.Property<long>("IdOrganization")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdOrganization");

                    b.ToTable("organization");
                });

            modelBuilder.Entity("SMS_TYNB.Models.Master.SmsConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.Property<string>("ApiPass")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ApiUser")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContractId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DataCoding")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("IsTelCoSub")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IssEnSms")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LabelId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SaleOrderId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UrlSms")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SmsConfig");
                });
#pragma warning restore 612, 618
        }
    }
}
